appwebserviexpress-main/Portafolios/Portafolios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
]

appwebserviexpress-main/Portafolios/core/urls.py
from django.urls import path
from . import views

app_name ='core'

urlpatterns = [
   path('', views.index, name='index'),
   path('perfil/', views.perfil, name='perfil'),
   path('perfil/<str:username>/', views.perfil, name='perfil'),
   path('reservar_hora/', views.reserva_de_hora, name='reserva_de_hora'),
   path('listar_reserva/', views.listar_reserva_hora, name='listar_reserva'),
   path('listar_reserva/<str:username>/', views.listar_reserva_hora, name='listar_reserva'),
   path('modificar_reserva/<id>/', views.modificar_reserva, name='modificar'),
   path('eliminar_reserva/<id>/', views.eliminar_reserva, name='eliminar'),
   path('nuestros_servicios/', views.nuestros_servicios, name='servicios'),
   path('afinacion/', views.afinacion, name='afinacion'),
   path('aire_acondicionado/', views.aire_acondicionado, name='aire_acondicionado'),
   path('alineacion/', views.alineacion, name='alineacion'),
   path('banda_distribucion/', views.banda_de_distribucion, name='banda_distribucion'),
   path('bateria/', views.bateria, name='bateria'),
   path('bomba_agua/', views.bomba_agua, name='bomba_agua'),
   path('caja_transferencia/', views.caja_transferencia, name='caja_transferencia'),
   path('cambio_aceite/', views.cambio_aceite, name='cambio_aceite'),
   path('cambio_llantas/', views.cambio_llantas, name='cambio_llantas'),
   path('frenos/', views.frenos, name='frenos'),
   path('direccion_hidraulica/', views.direccion_hidraulica, name='direccion_hidraulica'),
   path('luces/', views.luces, name='luces'),
   path('boleta/<id>/', views.boleta, name='boleta'),
   path('mensaje_reserva/', views.mensaje_reserva, name='mensaje_reserva'),
   path('mensaje_mod_reserva/', views.mensaje_modificar_reserva, name='mensaje_modificar_reserva'),
]

appwebserviexpress-main/Portafolios/usuarios/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('register/',views.register, name='registro'),
    path('login/',views.login, name='inicio_sesion'),
    path('logout/',views.logout, name='cerrar_sesion'),    
    path('mensaje_registro/',views.mensaje_registro, name='mensaje_registro'),  
    path('modificar_perfil/<id>', views.modificar_perfil, name='modificar_perfil'),
]

appwebserviexpress-main/Portafolios/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
{% block head %}
{% endblock head %}
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="{% static '/assets/img/header_logo_dark.png' %}" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <!-- CSS of Date and Time Pickers-->
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css" integrity="sha512-YdYyWQf8AS4WSB0WWdc3FbQ3Ypdm0QCWD2k4hgfqbQbRCJBEgX0iAegkl2S1Evma5ImaVXLBeUkIlP6hQ1eYKQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
{% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a href="{% url 'core:index' %}"> <img class="navbar-brand js-scroll-trigger imagen" width="180" src="{% static '/assets/img/header_logo_dark.png' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                    <div class="collapse navbar-collapse derecha" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto" >
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:index'%}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:servicios'%}">Servicios</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:perfil'%}">Perfil</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:reserva_de_hora'%}">Reserva Hora</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contacto">Contacto</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'usuarios:cerrar_sesion'%}">Cerrar Sesion</a></li>
                        </ul>
                    </div>
            </div>
        </nav>
{% else %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a href="{% url 'core:index' %}"> <img class="navbar-brand js-scroll-trigger imagen" width="180" src="{% static '/assets/img/header_logo_dark.png' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                    <div class="collapse navbar-collapse derecha" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:index'%}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:servicios'%}">Servicios</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" data-toggle="modal" data-target="#exampleModal">Reserva Hora</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contacto">Contacto</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'usuarios:inicio_sesion'%}">Iniciar Sesión</a></li>
                            
                        </ul>
                    </div>
            </div>
        </nav>    
         <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">¡Recuerda!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <p class="text-black">Para poder reservar una hora es necesario iniciar sesión, sino tiene cuenta registrese
                        <a href="{% url 'usuarios:registro'%}" class="alert-link">aquí</a></p>                    
                    </div>
                    
                    <div class="modal-footer">                        
                        <button type="button" class="btn btn-primary" onclick="location.href='{% url 'usuarios:inicio_sesion'%}'">Continuar</button>
                    </div>
                </div>
            </div>
        </div>
{% endif %}
        
{% block content %}
{% endblock content %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Date and Time Picker JS-->
        <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js" integrity="sha512-RCgrAvvoLpP7KVgTkTctrUdv7C6t7Un3p1iaoPr1++3pybCyCsCZZN7QEHMZTcJTmcJ7jzexTO+eFpHk4OCFAg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
<section class="contact-section bg-grey" id="contacto">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5">
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-map-marked-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Dirección</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-white-50">Avenida La Florida 2656, Santiago, Región Metropolitana</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-envelope text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Correo</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-white-50">contacto@serviexpress.cl</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-3 mb-md-0">
                        <div class="card py-4 h-100">
                            <div class="card-body text-center">
                                <i class="fas fa-mobile-alt text-primary mb-2"></i>
                                <h4 class="text-uppercase m-0">Fono</h4>
                                <hr class="my-4 mx-auto" />
                                <div class="small text-white-50">+56 9 85421258</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="social d-flex justify-content-center">
                    <a class="mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="mx-2" href="#!"><i class="fab fa-github"></i></a>
                </div>
            </div>
        </section>
</html>