appwebserviexpress-main/Portafolios/Portafolios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
]

appwebserviexpress-main/Portafolios/core/urls.py
from django.urls import path
from . import views

app_name ='core'

urlpatterns = [
   path('', views.index, name='index'),
   path('perfil/', views.perfil, name='perfil'),
   path('perfil/<str:username>/', views.perfil, name='perfil'),
   path('reservar_hora/', views.reserva_de_hora, name='reserva_de_hora'),
   path('listar_reserva/', views.listar_reserva_hora, name='listar_reserva'),
   path('listar_reserva/<str:username>/', views.listar_reserva_hora, name='listar_reserva'),
   path('modificar_reserva/<id>/', views.modificar_reserva, name='modificar'),
   path('eliminar_reserva/<id>/', views.eliminar_reserva, name='eliminar'),
   path('nuestros_servicios/', views.nuestros_servicios, name='servicios'),
   path('afinacion/', views.afinacion, name='afinacion'),
   path('aire_acondicionado/', views.aire_acondicionado, name='aire_acondicionado'),
   path('alineacion/', views.alineacion, name='alineacion'),
   path('banda_distribucion/', views.banda_de_distribucion, name='banda_distribucion'),
   path('bateria/', views.bateria, name='bateria'),
   path('bomba_agua/', views.bomba_agua, name='bomba_agua'),
   path('caja_transferencia/', views.caja_transferencia, name='caja_transferencia'),
   path('cambio_aceite/', views.cambio_aceite, name='cambio_aceite'),
   path('cambio_llantas/', views.cambio_llantas, name='cambio_llantas'),
   path('frenos/', views.frenos, name='frenos'),
   path('direccion_hidraulica/', views.direccion_hidraulica, name='direccion_hidraulica'),
   path('luces/', views.luces, name='luces'),
   path('boleta/<id>/', views.boleta, name='boleta'),
   path('mensaje_reserva/', views.mensaje_reserva, name='mensaje_reserva'),
   path('mensaje_mod_reserva/', views.mensaje_modificar_reserva, name='mensaje_modificar_reserva'),
]

appwebserviexpress-main/Portafolios/usuarios/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('register/',views.register, name='registro'),
    path('login/',views.login, name='inicio_sesion'),
    path('logout/',views.logout, name='cerrar_sesion'),    
    path('mensaje_registro/',views.mensaje_registro, name='mensaje_registro'),  
    path('modificar_perfil/<id>', views.modificar_perfil, name='modificar_perfil'),
]

appwebserviexpress-main/Portafolios/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class UsuarioWeb(AbstractUser):

    fecha_nacimiento    = models.DateField(verbose_name='fecha de nacimiento', null=True) 

    class Meta:
        managed = True
        db_table = 'usuarioweb'

appwebserviexpress-main/Portafolios/usuarios/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.forms.models import fields_for_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import UsuarioWeb

class RegistrationForm(UserCreationForm):

    first_name = forms.CharField(label='Nombre',required=True)
    last_name = forms.CharField(label='Apellidos',required=True)
    email = forms.EmailField(required=True)

    def clean_email(self):
        email = self.cleaned_data['email']
        if UsuarioWeb.objects.filter(email=email).exists():
            raise ValidationError("Ya exsite un usuario con este Email.")
        return email    

    class Meta:

        model = UsuarioWeb
        fields = ('username','first_name' ,'last_name' , 'email', 'password1', 'password2', 'fecha_nacimiento') 

    def __init__(self, *args, **kwargs):

        super(RegistrationForm, self).__init__(*args,**kwargs)


        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})

 
        for field in self.fields.values():
                field.help_text = None

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):

        super(LoginForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'input100'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})    

appwebserviexpress-main/Portafolios/usuarios/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import login as log_in, logout as log_out
from .auth import AuthenticationEmailBackend
from django.contrib.auth import authenticate
from usuarios.models import UsuarioWeb

def register(request):

    registration_form = RegistrationForm()

    if request.method == "POST":

        registration_form = RegistrationForm(data=request.POST)

        if registration_form.is_valid():

            user = registration_form.save()

            return redirect('usuarios:mensaje_registro')

            #username = registration_form.cleaned_data['username']
            #password = registration_form.cleaned_data['password1']

            #user = authenticate(username=username,password=password)

            #if user is not None:

                #log_in(request, user)

                #return redirect('core:index')


    return render(request, "usuarios/register.html", {'registration_form': registration_form})

def modificar_perfil(request, id):    

    perfil = UsuarioWeb.objects.get(id=id)

    formulario = RegistrationForm(instance=perfil)

    if request.method == 'POST':
        formulario = RegistrationForm(data=request.POST, instance=perfil)

        if formulario.is_valid():            

            formulario.save()           

            return redirect('core:perfil')



    return render(request, 'usuarios/modificar_perfil.html', {'form':formulario})


def mensaje_registro(request):

    return render(request,'usuarios/mensaje_registro.html',{})


def login(request):

    login_form = LoginForm()

    if request.method == "POST":
        print('pasa')
        login_form = LoginForm(data=request.POST)

        print(login_form.is_valid())
        if login_form.is_valid():

            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('core:index')

            user = AuthenticationEmailBackend(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('core:index')

    return render(request, 'usuarios/login.html',{'login_form':login_form})

def logout(request):

    log_out(request)

    return redirect('usuarios:inicio_sesion')

appwebserviexpress-main/Portafolios/usuarios/templates/usuarios/login.html
{% extends "base.html" %}

{% block head %}
<title>
    Inicio de Sesion
</title>
{% endblock head %}
{% load static %}
{% block content %}      


        <header class="container">
        	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
               
                        <div class="limiter">
                            <div class="container-login100">
                                <div class="wrap-login100">
                                    <div class="login100-form-title" style="background-image: url(images/bg-01.jpg);">
                                        <span class="login100-form-title-1">
                                            Iniciar Sesión
                                        </span>
                                    </div>
            
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                        <br>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group text-center">Usuario o Correo Electronico </div>
                                                </div>
                                                <div class="wrap-input100 input100">{{login_form.username}}</div>
                                            </div>
                                            <br>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group text-center">{{login_form.password.label}}</div>
                                                </div>           
                                                <div class="wrap-input100 input100">{{login_form.password}}</div>                                
                                            </div>
                                                        {% if login_form.errors %}
                                                <div class="col-md-12 d-flex justify-content-center alert alert-danger" role="alert"> Usuario o Contraseña incorrectos. </div>
                                                        {% endif %}                                                
                                            </div>
                                            <br>
                                            <div class="flex-sb-m w-full p-b-30">
                                            <div class="contact100-form-checkbox p-l-40" >
                                                <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                                                
                                            </div>

                                            
                                        </div>
                                        <br>
                                        <div class="container-login100-form-btn">
                                            <button class="login100-form-btn" type="submit">
                                                Ingresar
                                            </button>
                                        </div>
                                        <br>
                                        <div class="p-l-160">
                                            ¿No tienes cuenta?, Regístrate
                                                <a href="{% url 'usuarios:registro'%}">
                                                    ¡Aquí!
                                                </a>
                                        </div>
                                        <br>
                                        

                                        
                                        
                                    </form>                                
                                </div>
                            </div>
                        </div> <!-- /.8 -->

           
            
        </header>


{% endblock %}

appwebserviexpress-main/Portafolios/usuarios/templates/usuarios/mensaje_registro.html
{% extends "base.html" %}

{% block head %}
<title>
    Registro de Usuario
</title>
{% endblock head %}
{% load static %}
{% block content %}


                                                    
        <div class="masthead mt-5 pt-5">
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
        <br>        <br>
            <div class="container pt-5"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <div class="alert alert-success" role="alert">
                                        ¡Registrado Correctamente!
                                    </div>
                                        <div class="container-login100-form-btn p-l-160">
                                            <button class="login100-form-btn" type="submit" onclick="location.href='{% url 'usuarios:inicio_sesion'%}'">
                                                Aceptar
                                            </button>
                                        </div>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </div>
        



{% endblock %}

appwebserviexpress-main/Portafolios/usuarios/templates/usuarios/modificar_perfil.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Modificar Datos Perfil</title>
{% endblock head %}
{% block content %}


        <header class="masthead">       
        <br> 
        	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
            <link href="{% static 'css/estilo_slide.css' %}" rel="stylesheet" />
                
                        <div class="limiter">                        
                            <div class="container-login100">
                                <div class="wrap-login100">                                                                        
                                    <div class="logingreen-form-title">                                            
                                        <span class="logingreen-form-title-1">
                                            Modificar datos
                                        </span>                                        
                                    </div>
                                    <div class="container mt-3"> 
                                            <div class="alert alert-warning" role="alert">
                                                Para modificar sus datos sin cambiar su contraseña, por favor ingrese su contraseña actual en el campo de contraseña,
                                                de lo contrario puede cambiar su contraseña junto con sus datos.
                                            </div>
                                        <div class="card-body bg-light">
                                            <div class="container"> 
                                                <form role="form" method="POST">
                                                    {% csrf_token %}
                                                    <div class="controls">
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.username.label}}  {{form.username}} {{form.username.errors}}</div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.email.label}}  {{form.email}} {{registration_form.email.errors}}</div>
                                                            </div>
                                                        </div>
                                                    
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.fecha_nacimiento.label}}  {{form.fecha_nacimiento}} {{form.fecha_nacimiento.errors}}</div>
                                                            </div>                                           
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.first_name.label}} {{form.first_name}} {{form.first_name.errors}}</div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.last_name.label}} {{form.last_name}} {{form.last_name.errors}}</div>
                                                            </div>
                                                        </div>
                                                        <div class="row">
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.password1.label}} {{form.password1}} {{form.password1.errors}}</div>
                                                            </div>
                                                            <div class="col-md-6">
                                                                <div class="form-group">{{form.password2.label}} {{form.password2}}</div>
                                                            </div>
                                                            <div class="col-md-12">
                                                                <div class="form-group">{{form.password2.errors}}</div>
                                                            </div>
                                                        </div>
                                                            <div class="container-login100-form-btn">
                                                                <button class="login100-form-btn" type="submit">
                                                                    Guardar
                                                                </button>
                                                            </div>      

                                                            <dvi class="p-l-19 mt-2"><a href="{% url 'core:perfil' %}" class="p-l-250">Volver</a>      </div>                                                  
                                                        
                                                        
                                                    </div>
                                                </form> 
                                            </div>    
                                        </div>
                                    </div>    
                                </div>                                
                            </div> 
                        </div> 
                    
                    <br><br><br><br><br>
        </header>
        <script>
            $(function () {
            $("#id_fecha_nacimiento").datepicker({
                format:'dd/mm/yyyy',
            });
            });
        </script>

{% endblock %}

appwebserviexpress-main/Portafolios/usuarios/templates/usuarios/register.html
{% extends "base.html" %}

{% block head %}
<title>
    Registro de Usuario
</title>
{% endblock head %}
{% load static %}
{% block content %}
{% if registration_form.non_field_errors %}
    <div class="aler alert-danger" role="alert">
    {% for error in registration_form.non_field_errors %}
        {{error}}
    {% endfor %}
{% endif %}


        <header class="container">
        <br><br>
        	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
               
                        <div class="limiter">
                            <div class="container-login100">
                                <div class="wrap-login100">
                                    <div class="login100-form-title" style="background-image: url(images/bg-01.jpg);">
                                        <span class="login100-form-title-1">
                                            ¡Regístrate!
                                        </span>
                                    </div>
                                    <div class="container">
                                    <br>
                                        <form role="form" method="POST">
                                            {% csrf_token %}
                                            <div class="controls">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.username.label}}  {{registration_form.username}} {{registration_form.username.errors}}</div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.email.label}}  {{registration_form.email}} {{registration_form.email.errors}}</div>
                                                    </div>
                                                </div>
                                                <br>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.fecha_nacimiento.label}}  {{registration_form.fecha_nacimiento}} {{registration_form.fecha_nacimiento.errors}}</div>
                                                    </div>                                           
                                                </div>
                                                <br>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.first_name.label}} {{registration_form.first_name}} {{registration_form.first_name.errors}}</div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.last_name.label}} {{registration_form.last_name}} {{registration_form.last_name.errors}}</div>
                                                    </div>
                                                </div>
                                                <br>
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.password1.label}} {{registration_form.password1}} {{registration_form.password1.errors}}</div>
                                                    </div>
                                                    <div class="col-md-6">
                                                        <div class="form-group">{{registration_form.password2.label}} {{registration_form.password2}}</div>
                                                    </div>
                                                    <div class="col-md-12">
                                                        <div class="form-group">{{registration_form.password2.errors}}</div>
                                                    </div>
                                                    <br><br>  
                                                    <div class="container-login100-form-btn">
                                                        <button class="login100-form-btn">
                                                            Ingresar
                                                        </button>
                                                    </div>    

                                                    <div class="p-l-160 mt-4">
                                                        ¿Ya tienes una cuenta?, Ingresa
                                                        <a href="{% url 'usuarios:inicio_sesion'%}">
                                                            ¡Aquí!
                                                        </a>
                                                    </div>
                                                    
                                                    <br>   <br><br><br>                                           
                                                </div>
                                            </div>
                                        </form>
                                        
                                    </div>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
            <br>
            
            
        </header>
        
        <script>
            $(function () {
            $("#id_fecha_nacimiento").datepicker({
                format:'dd/mm/yyyy',
            });
            });
        </script>



{% endblock %}