appwebserviexpress-main/Portafolios/Portafolios/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('usuarios/', include('usuarios.urls')),
]

appwebserviexpress-main/Portafolios/core/urls.py
from django.urls import path
from . import views

app_name ='core'

urlpatterns = [
   path('', views.index, name='index'),
   path('perfil/', views.perfil, name='perfil'),
   path('perfil/<str:username>/', views.perfil, name='perfil'),
   path('reservar_hora/', views.reserva_de_hora, name='reserva_de_hora'),
   path('listar_reserva/', views.listar_reserva_hora, name='listar_reserva'),
   path('listar_reserva/<str:username>/', views.listar_reserva_hora, name='listar_reserva'),
   path('modificar_reserva/<id>/', views.modificar_reserva, name='modificar'),
   path('eliminar_reserva/<id>/', views.eliminar_reserva, name='eliminar'),
   path('nuestros_servicios/', views.nuestros_servicios, name='servicios'),
   path('afinacion/', views.afinacion, name='afinacion'),
   path('aire_acondicionado/', views.aire_acondicionado, name='aire_acondicionado'),
   path('alineacion/', views.alineacion, name='alineacion'),
   path('banda_distribucion/', views.banda_de_distribucion, name='banda_distribucion'),
   path('bateria/', views.bateria, name='bateria'),
   path('bomba_agua/', views.bomba_agua, name='bomba_agua'),
   path('caja_transferencia/', views.caja_transferencia, name='caja_transferencia'),
   path('cambio_aceite/', views.cambio_aceite, name='cambio_aceite'),
   path('cambio_llantas/', views.cambio_llantas, name='cambio_llantas'),
   path('frenos/', views.frenos, name='frenos'),
   path('direccion_hidraulica/', views.direccion_hidraulica, name='direccion_hidraulica'),
   path('luces/', views.luces, name='luces'),
   path('boleta/<id>/', views.boleta, name='boleta'),
   path('mensaje_reserva/', views.mensaje_reserva, name='mensaje_reserva'),
   path('mensaje_mod_reserva/', views.mensaje_modificar_reserva, name='mensaje_modificar_reserva'),
]

appwebserviexpress-main/Portafolios/usuarios/urls.py
from django.urls import path
from . import views

app_name='usuarios'

urlpatterns = [
    path('register/',views.register, name='registro'),
    path('login/',views.login, name='inicio_sesion'),
    path('logout/',views.logout, name='cerrar_sesion'),    
    path('mensaje_registro/',views.mensaje_registro, name='mensaje_registro'),  
    path('modificar_perfil/<id>', views.modificar_perfil, name='modificar_perfil'),
]

appwebserviexpress-main/Portafolios/core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from usuarios.models import UsuarioWeb
from django.db import models
from django.contrib.auth.models import AbstractUser


class Boleta(models.Model):
    id = models.BigAutoField(primary_key=True)
    servicio = models.ForeignKey('Servicio', on_delete=models.CASCADE,)
    fecha = models.DateTimeField()
    comentario = models.CharField(max_length=100, blank=True, null=True)
    total = models.IntegerField()
    id_user = models.IntegerField()
    nombre_cliente = models.CharField(max_length=100)
    nombre_servicio = models.CharField(max_length=30)    
    nombre_mecanico = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'boleta'


class Reservadehora(models.Model):
    id = models.BigAutoField(primary_key=True)
    fecha_solicitud = models.DateTimeField()
    asunto = models.CharField(max_length=200)
    tiposervicio = models.ForeignKey('Tiposervicio', on_delete=models.CASCADE)
    usuarioescritorio = models.ForeignKey('Usuarioescritorio', on_delete=models.CASCADE)
    usuarioweb = models.ForeignKey(UsuarioWeb, on_delete=models.CASCADE, related_name='reserva')

    class Meta:
        managed = True
        db_table = 'reservadehora'


class Servicio(models.Model):
    id = models.BigAutoField(primary_key=True)
    fecha = models.DateTimeField()
    comentario = models.CharField(max_length=200, blank=True, null=True)
    validado = models.BooleanField()
    reservadehora = models.ForeignKey(Reservadehora, on_delete=models.CASCADE)
    

    class Meta:
        managed = False
        db_table = 'servicio'


class Tiposervicio(models.Model):
    id = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=100)
    precio = models.IntegerField()

    def __str__(self):
        return self.descripcion

    class Meta:
        managed = False
        db_table = 'tiposervicio'


class Tipousuario(models.Model):
    id = models.BigAutoField(primary_key=True)
    descripcion = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'tipousuario'


class Usuarioescritorio(models.Model):
    id = models.BigAutoField(primary_key=True)
    tipousuario = models.ForeignKey(Tipousuario, on_delete=models.CASCADE)
    nombre_usuario = models.CharField(max_length=100)
    contrasena = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    primer_nombre = models.CharField(max_length=150)
    segundo_nombre = models.CharField(max_length=150, blank=True, null=True)
    apellido_paterno = models.CharField(max_length=150)
    apellido_materno = models.CharField(max_length=150)
    rut = models.IntegerField()
    dv = models.CharField(max_length=1)
    fecha_nacimiento = models.DateField()

    def __str__(self):
        nombre = self.primer_nombre + ' ' + self.apellido_paterno + ' ' + self.apellido_materno
        return nombre

    class Meta:
        managed = False
        db_table = 'usuarioescritorio'

appwebserviexpress-main/Portafolios/core/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from .models import Reservadehora, Usuarioescritorio, Boleta
from datetime import datetime, timedelta, date, tzinfo
from django.utils import timezone
from .models import Reservadehora
from django.core.exceptions import ValidationError
import pytz


class ReservadeHoraForm(forms.ModelForm):
    
    asunto = forms.CharField(widget=forms.Textarea(attrs={'rows':4}))
    hora = forms.CharField()
    
    def clean_fecha_solicitud(self):
        fecha_solicitud = self.cleaned_data['fecha_solicitud']
        if fecha_solicitud < (timezone.now() + timedelta(days=-1)):
            raise ValidationError("Fecha del pasado.")
        
        return fecha_solicitud
    
    def clean_hora(self):
        horas_permitidas = ['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45'
                            ,'11:00','11:15','11:30','11:45','12:00','12:15','12:30','13:00'
                            ,'13:15','13:30','13:45','14:00','14:15','14:30','14:45','15:00'
                            ,'15:15','15:30','15:45','16:00','16:15','16:30','16:45','17:00'
                            ,'17:15','17:30','17:45','18:00','18:15','18:30','18:45','19:00'
                            ,'19:15','19:30','19:45','20:00','20:15','20:30','20:45']

        hora = self.cleaned_data['hora']
        if hora not in horas_permitidas:
            raise ValidationError("Hora no valida.")
        
        return hora
    class Meta:
        model = Reservadehora
        fields = ('fecha_solicitud','asunto','tiposervicio','usuarioescritorio')

    def clean(self):
        data = self.cleaned_data
        if not ('fecha_solicitud' in data.keys() and 'hora' in data.keys()):
            raise forms.ValidationError("Este campo es requerido.")  
        fecha_solicitudd = data['fecha_solicitud']
        fecha_solicitudd = fecha_solicitudd.date()
        hora = data['hora']
        fecha = str(fecha_solicitudd) + ' ' + str(hora)
        print('fecha str:',fecha)
        fecha_f = datetime.strptime(fecha, "%Y-%m-%d %H:%M")
        print('fecha 1er strptime:',fecha_f)
        fecha_formato = fecha_f.strftime("%d/%m/%Y %H:%M")
        print('fecha formato cambiado:',fecha_formato)
        fecha_f = datetime.strptime(fecha_formato,"%d/%m/%Y %H:%M")
        fechas = Reservadehora.objects.filter(fecha_solicitud=fecha_f).count()
        if fechas >= 1:
            raise forms.ValidationError("Fecha no disponible.")
        return data
    
    def __init__(self, *args, **kwargs):

        super(ReservadeHoraForm, self).__init__(*args,**kwargs)
        self.fields['usuarioescritorio'] = forms.ModelChoiceField(queryset=Usuarioescritorio.objects.filter(tipousuario_id=5))

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})
            self.fields[field].widget.attrs.update({'autocomplete': 'off'})

        self.fields['hora'].widget.attrs.update({'class': 'form-control timepicker'})        


class BoletaForm(forms.ModelForm):

    

    class Meta:
        model = Boleta
        fields = '__all__'

appwebserviexpress-main/Portafolios/core/views.py
from django.db.backends.utils import CursorDebugWrapper
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ReservadeHoraForm, BoletaForm
from django.db import connection
from .models import Reservadehora, Boleta
from usuarios.models import UsuarioWeb
from usuarios.forms import RegistrationForm

def index(request):

    return render(request,'core/index.html',{})

@login_required(login_url='/usuarios/login/')
def reserva_de_hora(request):

    form_reserva = ReservadeHoraForm()

    if request.method == 'POST':
        
        form_reserva = ReservadeHoraForm(data=request.POST)

        if form_reserva.is_valid():

            fecha_solicitud = form_reserva.data['fecha_solicitud']
            hora = form_reserva.data['hora']
            asunto = form_reserva.data['asunto']
            tiposervicio = form_reserva.data['tiposervicio']
            usuarioescritorio = form_reserva.data['usuarioescritorio']
            usuarioweb = request.user.id
            print(request.user.id)
            print(fecha_solicitud)
            print(hora)
            fecha = fecha_solicitud + ' ' + hora
            print(fecha)


            with connection.cursor() as cursor:
                cursor.callproc('PKG_RESERVADEHORA.PR_AGREGAR_RESERVADEHORA',[fecha,asunto,tiposervicio,usuarioescritorio,usuarioweb])
            
            return redirect('core:mensaje_reserva')


    return render(request,'core/reserva_de_hora.html',{'form':form_reserva})

@login_required(login_url='/usuarios/login/')
def perfil(request, id=None):
    current_user = request.user

    if id and id != current_user.id:
        user = UsuarioWeb.objects.get(id=id)
        
    else:
        
        user = current_user

    return render(request,'core/perfil.html',{'user':user})

def lista_perfil():

    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    out_cur = django_cursor.connection.cursor()

    cursor.callproc()


@login_required(login_url='/usuarios/login/')
def listar_reserva_hora(request, id=None):   
    current_user = request.user

    if id and id != current_user.id:
        user = UsuarioWeb.objects.get(id=id)
        reserva = user.reserva.get(id=id)
    else:
        reserva = current_user.reserva.all()
        user = current_user

    data = {
        'reservadehora': listar_reserva()
    }

    return render(request,'core/listar_reservar_hora.html', {'data':data,'user':user, 'reserva':reserva})

def listar_reserva():

    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    out_cur = django_cursor.connection.cursor()

    cursor.callproc("PKG_RESERVADEHORA.PR_LISTAR_RESERVADEHORA", [out_cur])

    
    lista = []
    for fila in out_cur:
        lista.append(fila)

    return lista


def modificar_reserva(request, id=None):

    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    
    reserva = Reservadehora.objects.get(id=id)

    
    formulario = ReservadeHoraForm(instance=reserva)
    
    
    if request.method == 'POST':
        formulario = ReservadeHoraForm(data=request.POST, instance=reserva)
        
        if formulario.is_valid():

            reservahora_id = reserva.id
            fecha = formulario.data['fecha_solicitud']
            asunto = formulario.data['asunto']
            tiposervicio = formulario.data['tiposervicio']
            usuarioescritorio = formulario.data['usuarioescritorio']
            usuarioweb = request.user.id

            formulario.save()
            
            return redirect('core:mensaje_modificar_reserva')
        
        
            
    return render(request,'core/modificar_reserva.html', {'formulario':formulario})



def modificar(reservahora_id,fecha,asunto,tiposervicio,usuarioescritorio,usuarioweb):

    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()

    cursor.callproc('PKG_RESERVADEHORA.PR_ACTUALIZAR_RESERVADEHORA',[reservahora_id,fecha,asunto,tiposervicio,usuarioescritorio,usuarioweb])

    return cursor



def eliminar_reserva(request, id):  

    django_cursor = connection.cursor()
    cursor = django_cursor.connection.cursor()
    reserva = get_object_or_404(Reservadehora, id=id)
    
    cursor.callproc('PKG_RESERVADEHORA.PR_BORRAR_RESERVADEHORA', [id])
    return redirect('core:listar_reserva')
    

def nuestros_servicios(request):


    return render(request, 'core/nuestros_servicios.html', {})


def afinacion(request):

    return render(request, 'core/afinacion.html', {})

def aire_acondicionado(request):

    return render(request, 'core/aire_acondicionado.html', {})

def alineacion(request):

    return render(request, 'core/alineacion.html', {})

def banda_de_distribucion(request):

    return render(request, 'core/banda_de_distribucion.html', {})

def bateria(request):

    return render(request, 'core/bateria.html', {})

def bomba_agua(request):

    return render(request, 'core/bomba_agua.html', {})

def caja_transferencia(request):

    return render(request, 'core/caja_transferencia.html', {})

def cambio_aceite(request):

    return render(request, 'core/cambio_aceite.html', {})

def cambio_llantas(request):

    return render(request, 'core/cambio_llantas.html', {})

def frenos(request):

    return render(request, 'core/frenos.html', {})

def direccion_hidraulica(request):

    return render(request, 'core/direccion_hidraulica.html', {})

def luces(request):

    return render(request, 'core/luces.html', {})

def boleta(request, id):
    

    boleta = Boleta.objects.get(id_user=id)    


    return render(request, 'core/boleta.html', {'boleta':boleta})

def mensaje_reserva(request):

    return render(request, 'core/mensaje_reserva.html', {})


def mensaje_modificar_reserva(request):

    return render(request, 'core/mensaje_modificar_reserva.html', {})

appwebserviexpress-main/Portafolios/core/templates/core/afinacion.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Afinación</title>
{% endblock head %}
{% block content %}
        <header class="masthead">
                <link href="{% static 'css/servicios.css' %}" rel="stylesheet"/>
                <link href="{% static 'css/descripcion.css' %}" rel="stylesheet" />
                <link href="{% static 'css/afinacion.css' %}" rel="stylesheet" />
        <br>       <br>
            <div class="container afinacion mt-5 pt-5">
                <div class="row">
                    <h2 class="text-white mb-4">Afinacion</h2>
                </div>
                <div class="row">
                    <div class="col-4">
                        <img class="iclass" src="{% static '/assets/img/afinacion2.jpg' %}"/>
                    </div>
                    <div class="col-8">
                        <p class="text-white-80">
                                        El servicio de afinación de un coche consiste en la sustitución de las piezas que por su uso normal se desgastan disminuyendo su rendimiento, 
                                        y la limpieza a profundidad de algunos elementos del motor.
                        </p>
                    </div>
                </div>
            </div>   
            <div class="container afinacion mt-5">
                <div class="row">
                    <h2 class="text-white mb-4">¿Qué incluye la afinacion?</h2>
                </div>
                <div class="row">
                    <div class="col-4">
                        <img class="iclass" src="{% static '/assets/img/afinacion.jpg' %}"/>
                    </div>
                    <div class="col-8">
                        <p class="text-white-80">
                                        La afinación consiste en cambios de bujías, filtros de aceite y gasolina, cambio de aceite y limpieza de válvulas, todo ello da una garantía para alargar la vida útil del motor, 
                                        permite además obtener un buen rendimiento en consumo de gasolina.
                        </p>
                    </div>
                </div>
            </div>           
            
        </header>        
{% endblock content %}

appwebserviexpress-main/Portafolios/core/templates/core/eliminar_reserva.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Eliminar de Reserva de Hora</title>
{% endblock head %}
{% block content %}

appwebserviexpress-main/Portafolios/core/templates/core/listar_reservar_hora.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Lista de Reserva de Hora</title>
{% endblock head %}
{% block content %}

      
        <link href="{% static 'css/estilo_slide.css' %}" rel="stylesheet" />
        <br>   <br>    
            <header class="container">
        	<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
	        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
               
                        <div class="limiter">
                            <div class="container-listar ">
                                <div class="wrap-listar">
                                    <div class="logingreen-form-title" style="background-image: url(images/bg-01.jpg);">
                                        <span class="logingreen-form-title-1">
                                            Mi Historial de Reservas
                                        </span>
                                    </div>           
                
                <div class="row">
                    <div class=" ml-auto mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <div class="row"> 
                                        <div class="col-md-12 p-l-1 p-r-250">
                                            <div class="p-r-230"><div class="form-group p-r-250"><a class="p-r-250" href="{% url 'core:perfil' %}">Volver</a></div></div>
                                    </div>
                                    <table>
                                        <tr>
                                            <thead><th>ID Reserva Hora</th>  
                                            <th>Usuario</th>
                                            <th>Fecha Solicitud</th>
                                            <th>Asunto</th>
                                            <th>Tipo de Servicio</th>
                                            <th>Mecánico</th>
                                            <th></th>
                                            <th>Opciones</th>
                                            <th></th>
                                            </thead> 
                                            
                                        </tr>
                                        
                                        
                                        
                                        
                                        {% for r in reserva%}
                                        

                                        <tr>
                                            <td style="text-transform:uppercase;">{{ r.id | title }}</td>
                                            <td style="text-transform:uppercase;">{{ user.username | title }}</td>
                                            <td style="text-transform:uppercase;">{{ r.fecha_solicitud | title }}</td>
                                            <td style="text-transform:uppercase;">{{ r.asunto }}</td>
                                            <td style="text-transform:uppercase;">{{ r.tiposervicio }}</td>
                                            <td style="text-transform:uppercase;">{{ r.usuarioescritorio.primer_nombre}}&nbsp;{{r.usuarioescritorio.apellido_paterno}}</td>   
                                            <td>
                                            <a href="{% url 'core:modificar' r.id %}"> <img class="navbar-brand js-scroll-trigger" width="40" src="{% static '/assets/img/edit.png' %}"></a>
                                            </td> 
                                            <td>
                                            <a href="{% url 'core:eliminar' r.id %}"> <img class="navbar-brand js-scroll-trigger" width="40" src="{% static '/assets/img/delete.png' %}"></a>
                                            </td>    
                                            
                                            <td>
                                            <a href="{% url 'core:boleta'  r.id %}"> <img class="navbar-brand js-scroll-trigger" width="40" src="{% static '/assets/img/boleta.png' %}"></a>
                                            </td>     
                                                         
                                        </tr>
                                        
                                        {% endfor %}
                                        
                                    </table>
                                
                                
                                </div>
                                
                            </div>
                            
                        </div> <!-- /.8 -->
                    </div>
                    <br> <!-- /.row-->
                </div>
            </div>
            </div>
        </header>
        



{% endblock content %}

appwebserviexpress-main/Portafolios/core/templates/core/nuestros_servicios.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <title>Servicios</title>
{% endblock head %}
{% block content %}
        <header class="masthead">
                <link href="{% static 'css/servicios.css' %}" rel="stylesheet"/>
                <link href="{% static 'css/descripcion.css' %}" rel="stylesheet" />
                <link href="{% static 'css/afinacion.css' %}" rel="stylesheet" />
        <br>       <br>
        
            <div class='container servicios mt-5 pt-5'>
            <div class="container text-white">
                &nbsp;&nbsp;&nbsp;&nbsp;<span class="fs-80 text-center ml-5 pl-5 ">&nbsp;&nbsp;&nbsp;Nuestros Servicios</span>
            </div>               
                <div class="row pt-5">
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass" src="{% static '/assets/img/afinacion.jpg' %}"/>
                            <div class="item-text">
                                <a href="{% url 'core:afinacion' %}"><h5>afinacion</h5></a>
                                <p>$25.000 </p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass1" alt='frenos'  src="{% static '/assets/img/frenos.jpg' %}"/>
                            <div class="item-text">
                                <a href="{% url 'core:frenos' %}"><h5>frenos</h5></a>
                                <p>$93.990 </p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='aire acondicionado' src="{% static '/assets/img/AireAcondicionado_big.png' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:aire_acondicionado' %}"><h5>aire acondicionado</h5></a>
                                <p>$59.990 </p>
                            </div>
                        </div>
                    </div>  
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass1" alt='Alineacion'  src="{% static '/assets/img/ALINEACION.JPG' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:alineacion' %}"><h5>Alineacion</h5></a>
                                <p>$25.000</p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='Direccion hidraulica' src="{% static '/assets/img/DIRECCIONHIDRAULICA.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:direccion_hidraulica' %}"><h5>Direccion Hidraulica</h5></a>
                                <p>$65.990 </p>
                            </div>
                        </div>
                    </div>  
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass1" alt='llantas' src="{% static '/assets/img/LLANTAS.png' %}"/>
                            <div class="item-text">
                                <a href="{% url 'core:cambio_llantas' %}"><h5>cambio de llantas</h5></a>
                                <p>$150.990 </p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='bateria.jpg' src="{% static '/assets/img/bateria.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:bateria' %}"><h5>Bateria</h5></a>
                                <p>$34.990</p>
                            </div>
                        </div>
                    </div>  
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass1" alt='cambio aceite' src="{% static '/assets/img/cambio-aceite.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:cambio_aceite' %}"><h5>cambio aceite</h5></a>
                                <p>$30.000 </p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='banda de distribucion' src="{% static '/assets/img/bandadistribucion.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:banda_distribucion' %}"><h5>banda distribucion</h5></a>
                                <p>$55.550 </p>
                            </div>
                        </div>
                    </div>   
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='luces' src="{% static '/assets/img/luces.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:luces' %}"><h5>luces</h5></a>
                                <p>$30.000</p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='bomba agua' src="{% static '/assets/img/bombaagua.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:bomba_agua' %}"><h5>bomba agua</h5></a>
                                <p>$70.000 </p>
                            </div>
                        </div>
                    </div>
                    <div class="item col-lg-3 col-md-4 col-6">
                        <div class="item_service">
                            <img class="iclass2" alt='caja transferencia' src="{% static '/assets/img/cajadetransferencia.jpg' %}"/>
                            <div class="item-text">
                            <a href="{% url 'core:caja_transferencia' %}"><h5>caja transferencia </h5></a>
                                <p>$200.000 </p>
                            </div>
                    </div>
            

    
    
    </div>
            
        </header>        
{% endblock content %}